### PR TITLE
Implement YAML serialization

### LINKED ISSUE #127: Calling to_yaml on an ActiveType::Object does not serialize correctly
Calling `to_yaml` on a `ActiveType::Object` does not serialize its attributes whereas `to_json` does and works as expected. 

I am willing to PR a fix for this by overriding the `init_with`, `encode_with` methods as defined in [`ActiveRecord::Core`](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activerecord/lib/active_record/core.rb#L318) (used by Psych) and adding a Yaml encoder similar to `ActiveModel::AttributeSet::YAMLEncoder` to serialize the `virtual_attributes` field instead of `@attributes` as is currently done by the implementation in ActiveRecord.

**Example**
```ruby
class Person < ActiveType::Object
  attribute :name
end
p = Person.new(name: "Chris")
p.to_yaml
# => "--- !ruby/object:Person\nconcise_attributes: []\nnew_record: true\nactive_record_yaml_version: 2\n"
```

### PR DESCRIPTION
**Pull request by chriscz**
This implements YAML serialization in a way that's (hopefully) completely compatible with ActiveRecord's current and previous implementation. Closes #127

### CODE REVIEW

**Comment by chriscz** [comment]
I just started thinking that maybe passing an option such as `deep:true` to `to_yaml` or a may be useful if someone is interested in including all the `nests_one` and `nests_many` associations as well. What do you think @kratob?

**Comment by kratob** [comment]
The PR itself is perfect, I'll merge and release it. Thank you very much.

As to the `deep: true`: I think this would probably get messy and is in most (maybe all?) cases not necessary.

Just looking at our `nests_many` example from the docs
```
class Holiday < ActiveRecord::Base
end

class HolidaysForm < ActiveType::Object
  nests_many :holidays, reject_if: :all_blank, default: proc { Holiday.all }
end
```

I don't think it makes much sense to serialize all `Holiday` records together with the `ActiveType::Object`, because it's totally unclear what you would even do when deserializing.

Maybe I'm missing a usecase here, so feel free to reopen if you have a good idea.

**Comment by kratob** [comment]
Released as 1.5.0.

**Comment by chriscz** [comment]
Thanks @kratob I see what you mean in terms of the forms example. We've been using the library in some web integrations for representing the remote resources and we then serialize responses to using YAML. Fortunately these models are mostly flat so I don't really care for the `nests_{one,many}`, but we do have certain tree-like structures in other places, regardless, this isn't currently a requirement for me!

Thanks again for merging and your work on maintaining this project!

**Pull request merged**
