### PR TITLE
Support uuid for nest association

### PR DESCRIPTION
**Pull request by zetavg**
In Rails 5, it is convenient to set uuid as the id for models. However, the current implementation of this gem assumes that the type of id will always be an integer. In my opinion, I think that using string instead of integer will be more general, so I create this PR to show my suggested changes, hoping that we can have some discuss on this if necessary :)

### CODE REVIEW

**Comment by zetavg** [comment]
Oh I saw the CI errors, sorry that I forgot to check the tests, will fix them later.

**Comment by kratob** [comment]
You're right, it is unwise to assume the `id` to be an integer, (or actually for the primary key to be called `id` as well). I'm fine with merging this when tests pass.
I suspect you need to touch the `#fetch_child` method as well in order to fix the test failures.

**Comment by zetavg** [comment]
I discovered that simply removing `.to_i` will make String as id work 🎉. Some test cases are added as a guarantee of this feature.

**Comment by kratob** [comment]
Thanks for the fix! I've released it as 0.7.3.

**Comment by zetavg** [comment]
Thanks for the appreciation 🎉

**Pull request merged**
