### PR TITLE
Improve dirty tracking for virtual attributes

### PR DESCRIPTION
**Pull request by lowski**
This is WIP for #107.

### CODE REVIEW

**Comment by lowski** [comment]
@kratob  I've implemented basic version of `changed?` and `changes` for virtual attributes.
For `ActiveType::Record` I believe we need to discard changes on virtual attributes after save, right? Otherwise `changed?` and `changes` might not work correctly:

```ruby
class SignUp < ActiveType::Object[User]
  attribute :terms_accepted
end

sign_up = SignUp.new(email: "user@example.com", password: "123456", terms_accepted: true)
sign_up.save
sign_up.changes
#> {"terms_accepter" => [nil, true]}
```

However I need to write a test case for that scenario to be 100% sure.

I'm also wondering whether we need to implement `#{name}_will_change`, `changes_applied` and `restore_attributes` methods. For `ActiveType::Object` I would assume that new values are not apply'able as the object is not backed by database. WDYT?

**Comment by kratob** [comment]
I think expected behavior for `ActiveType::Record` would be to keep the value of virtual attributes after save, but no longer show them as changed (which would also require a change to the `<virtual_attribute>_changed?` methods. This makes things a bit more complicated since we would need to track the "saved" state of virtual attributes.

The longer I look at this the less sure I am about it. I feel like the way we currently handle virtual attributes will make it very hard to write a "correct" dirty tracking implementation. Not only would we potentially need the methods you mentioned, but what about the `#attribute_before_last_save`, `#attribute_in_database`, `#will_save_change_to_attribute?` and all the other methods, plus the fact that these methods don't even work the same across different versions of active_record.

On the one hand, we could be pragmatic, and consider the changes in the PR an objective improvement, and not worry too much that we have not implemented all cases.

On the other hand, it it would probably be less surprising to simply stop doing any kind of dirty tracking for virtual attributes, but then at least be consistent about it.

**Comment by lowski** [comment]
Thanks @kratob for your feedback.

Actually I’m working on very simple dirty tracking for virtual attributes - as you mentioned making the system 100% compatible with ActiveRecord would be complicated so it just checks previous and current values + implement changes_applied. I will update PR once I finish implementing them.

**Comment by lowski** [comment]
@kratob I've updated PR. Please let me know what you think.

**Comment by kratob** [comment]
I think that looks pretty good. You potentially might want to add `@virtual_attributes_were` here as wel: https://github.com/makandra/active_type/blob/master/lib/active_type/virtual_attributes.rb#L125

However, one issue you will probably run into is that ActiveType is still tested against AR 3.2, which apparently does not define `changes_applied`. We can either
- add some kind of version switch
- drop support for 3.2 (needs to happen at some point anyways)

**Comment by lowski** [comment]
@kratob thanks again for the feedback.

> You potentially might want to add @virtual_attributes_were here as well: https://github.com/makandra/active_type/blob/master/lib/active_type/virtual_attributes.rb#L125

Thanks for the pointer. I will apply that suggestion.

> However, one issue you will probably run into is that ActiveType is still tested against AR 3.2, which apparently does not define changes_applied.

I haven't worked with Rails 3.2 for a few years so I wasn't even aware of that. Thanks for the reminder :).

> add some kind of version switch

I'm not sure about this as It would make dirty tracking inconsistent between Rails versions so upgrading might be more difficult. I'm wondering if some warning (i.e. "Rails 3.2 does support `changes_applied` on `ActiveModel::Dirty` so dirty tacking on virtual attributes works only for initial values (nil)") on dirty tracking related methods (`#{name}_changed?`, `changed?`, `changes`, etc.) would be good enough for Rails 3.2. WDYT?

> drop support for 3.2 (needs to happen at some point anyways)

I think that would be the best option. If those changes could be included as part of version `1.2.0` then I believe we can drop support for Rails 3.2. However it would require more cleanup as there are other places with code targeting version 3.2. I can try to remove those once we decide go choose this way.

I'm looking forward to your response.

**Comment by kratob** [comment]
> > add some kind of version switch
> 
> I'm not sure about this as It would make dirty tracking inconsistent between Rails versions so upgrading might be more difficult. I'm wondering if some warning (i.e. "Rails 3.2 does support `changes_applied` on `ActiveModel::Dirty` so dirty tacking on virtual attributes works only for initial values (nil)") on dirty tracking related methods (`#{name}_changed?`, `changed?`, `changes`, etc.) would be good enough for Rails 3.2. WDYT?

I'd be okay if in 3.2 the behaviour stays as is, which would probably mean
- not defining the `changes_applied` method in 3.2
- skipping / adjusting some tests for 3.2
- I would not add a warning. We could mention it in the README / Changelog.

**Comment by lowski** [comment]
@kratob can you check my latest changes? I've added conditional switcher.

Btw. I believe the README is really outdated:

- there is no task: `all:install`
- `VERSION=4.2.1.pg rake` run all tests instead of just single version.

I was testing it manually by providing different `Gemfile` file:

- `BUNDLE_GEMFILE=Gemfile.3.2.sqlite3 bundle exec rspec`
- `BUNDLE_GEMFILE=Gemfile.4.2.pg bundle exec rspec`
- `BUNDLE_GEMFILE=Gemfile.5.2.pg bundle exec rspec`

**Comment by kratob** [comment]
Looks good to me. Thank you!

**Comment by kratob** [comment]
> Btw. I believe the README is really outdated:

You're right. Will update.

**Comment by kratob** [comment]
Relased as version 1.1.1.

**Pull request merged**
