### PR TITLE
RSpec 3

### PR DESCRIPTION
**Pull request by dlackty**

### CODE REVIEW

**Comment by henning-koch** [comment]
Thanks for the PR @dlackty .

The conversion revealed un ugly wart of RSpec, that `be_true` was always actually `be_truthy`. We should probably replace all the occurences of `be_truthy` to `eq(true)` and of `be_falsy` to `eq(false)` since that is what we wanted to test.

One last nitpick: The conversion of ...

```
it { should have(1).error_on(:persisted_string) }
```

... should be this:

```
it { is_expected_to have(1).error_on(:persisted_string) }
```

**Comment by dlackty** [comment]
Hey @henning-koch, an additional gem is required to use `have` matcher: https://github.com/rspec/rspec-collection_matchers

Is that ok for you? Also could I put rspec & this gem into gemspec as development dependency?

**Comment by henning-koch** [comment]
I didn't know about the extra gim. Let's stick with your original change then.

Regarding the development dependencies: We don't really care about these since we're using various [`Gemfiles`](https://github.com/makandra/active_type/tree/master/gemfiles) to run tests on various Rails versions and AR adapters. The gemspec is simply not expressive enough to specify multiple versions of gems.

**Comment by dlackty** [comment]
Updated. 
However, there's some test failure after changing `be_truthy` to `eq(true)`. Are those failure expected? Should I change the code behaviour or the test?

**Comment by henning-koch** [comment]
The failures were caused by a weird test. I merged your changes to `master` and fixed the failure.

Thanks for your contribution!

**Pull request merged**
