### PR TITLE
index_errors option to nests_many

### PR DESCRIPTION
**Pull request by cerdiogenes**
I will write tests for it soon, I opened the pull-request to get feedback.

### CODE REVIEW

**Comment by triskweline** [comment]
Is this a feature that exists in vanilla ActiveRecord? I'm not familiar with it, maybe you can point to documentation that describes the intended behavior?

**Comment by cerdiogenes** [comment]
This is a Rails 5 feature: https://github.com/rails/rails/pull/19686

**Comment by triskweline** [comment]
OK thanks.

Code looks good. I would maybe resolve the expression `!@options[:index_errors] && !ActiveRecord::Base.index_nested_attribute_errors` in the constructor instead of during validations.

We can merge it once tests are in place.

**Comment by cerdiogenes** [comment]
@triskweline did you noticed my last commits to this?

**Comment by triskweline** [comment]
I'm afraid Github doesn't send a notifications when new commits a pushed to an existing PR.

Looks good now, thanks!

I just released these changes as `0.7.0`.

**Pull request merged**
